## trainer
run_test: true
batch_size: 1
checkpoint_dir: ./models
checkpoint_name: checkpoint100.pth
test_result_dir: ./results/checkpoint100

beta1 : 1
beta2 : 0.1

## dataloader
num_workers: 1
image_size: 64
load_gt_depth: false
test_data_dir: ./datasets/test

## model
model_name: kdfrevs3d_gru
min_depth: 0.9
max_depth: 1.1
xyz_rotation_range: 60  # (-r,r) in degrees
xy_translation_range: 0.1  # (-t,t) in 3D
z_translation_range: 0  # (-t,t) in 3D
lam_perc: 1
lam_flip: 0.5
LoR_K: 64

## renderer
rot_center_depth: 1.0
fov: 10  # in degrees
tex_cube_size: 2
